Q.1 a) Write python code to create two arrays of 9 random number from uniform distribution b)
Convert it to (3*3)
c) Multiply two reshaped arrays

In [2]:
import numpy as np

In [2]:
arr1 = np.random.uniform(0,1,9)
arr1

array([0.20006425, 0.24635426, 0.78407519, 0.99677439, 0.67518457,
       0.71066051, 0.76658852, 0.9119027 , 0.46236852])

In [3]:
arr2 = np.random.uniform(0,1,9)
arr2

array([0.57002322, 0.27152594, 0.04510701, 0.82480261, 0.01043667,
       0.36919943, 0.2270364 , 0.81346449, 0.76472045])

In [4]:
arr1 = arr1.reshape(3,3)
arr1

array([[0.20006425, 0.24635426, 0.78407519],
       [0.99677439, 0.67518457, 0.71066051],
       [0.76658852, 0.9119027 , 0.46236852]])

In [5]:
arr2 = arr2.reshape(3,3)
arr2

array([[0.57002322, 0.27152594, 0.04510701],
       [0.82480261, 0.01043667, 0.36919943],
       [0.2270364 , 0.81346449, 0.76472045]])

In [6]:
arr = arr1*arr2
arr

array([[0.11404127, 0.06689157, 0.03536729],
       [0.82214211, 0.00704668, 0.26237545],
       [0.1740435 , 0.74180046, 0.35358266]])

Q.2 list1 = [23, 34, 43, 58, 25]
a) Convert list1 to array
b) Write a python code to calculate the sum of all elements in the given list using
NumPy?
c) Subtract 5 from each element of the array

In [7]:
list1 = [23, 34, 43, 58, 25]
list1 = np.array(list1)
list1

array([23, 34, 43, 58, 25])

In [8]:
np.sum(list1)

183

In [9]:
for i in list1:
    print(i-5)

18
29
38
53
20


Q.3 Write a python program to solve the following questions.
List1 = [ i for i in range (1,5)]
a) Convert this list to an array.
b) Convert array into (2*2) dimension
c) Create a diagonal matrix with diagonal elements in list1

In [4]:
List1 = [ i for i in range (1,5)]
List1

[1, 2, 3, 4]

In [11]:
List1 = np.array(List1)
List1

array([1, 2, 3, 4])

In [12]:
List1.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [6]:
np.diagflat(List1)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

Q.4 Write a python code to find even and odd numbers between (1,101)?

In [14]:
for i in range(1,101):
    if i % 2 == 0:
        print("Number is even: ", i)
    if i % 2 != 0:
        print("Number is odd: ", i)

Number is odd:  1
Number is even:  2
Number is odd:  3
Number is even:  4
Number is odd:  5
Number is even:  6
Number is odd:  7
Number is even:  8
Number is odd:  9
Number is even:  10
Number is odd:  11
Number is even:  12
Number is odd:  13
Number is even:  14
Number is odd:  15
Number is even:  16
Number is odd:  17
Number is even:  18
Number is odd:  19
Number is even:  20
Number is odd:  21
Number is even:  22
Number is odd:  23
Number is even:  24
Number is odd:  25
Number is even:  26
Number is odd:  27
Number is even:  28
Number is odd:  29
Number is even:  30
Number is odd:  31
Number is even:  32
Number is odd:  33
Number is even:  34
Number is odd:  35
Number is even:  36
Number is odd:  37
Number is even:  38
Number is odd:  39
Number is even:  40
Number is odd:  41
Number is even:  42
Number is odd:  43
Number is even:  44
Number is odd:  45
Number is even:  46
Number is odd:  47
Number is even:  48
Number is odd:  49
Number is even:  50
Number is odd:  51
Number is even:

Q.5 Define a function to check whether a number is in a range (100,1000) or not in range?


In [15]:
def test_range(x):
    if x in range(100,1000):
        print( " %s is in the range"% str(x))
    else :
        print("The number is outside the given range.")
test_range(999)

 999 is in the range


Q.6 Write a python code to find the factorial of any given number using a user-defined
function?

In [3]:
def fact(n):
      if n == 0 or n == 1:
        return 1 
      else:
        return (n * fact(n-1))
n = 10
print(fact(n))

3628800


Q.7 arr1 = np.array ([[545,421,156],
[250,157,166],
[640,325,356],
[282,570,753]])
Calculate Mean, Minimum, Maximum and SD of given array

In [8]:
arr1 = np.array ([[545,421,156], [250,157,166], [640,325,356], [282,570,753]])
arr1

array([[545, 421, 156],
       [250, 157, 166],
       [640, 325, 356],
       [282, 570, 753]])

In [19]:
np.mean(arr1)

385.0833333333333

In [9]:
arr1.mean()

385.0833333333333

In [20]:
np.min(arr1)

156

In [21]:
np.max(arr1)

753

In [23]:
arr1.std()

193.05243602595527